= Compendium for the End of the World

The Paranoid Doomsayer's Handbook

This guide is meant to aid survival when society finally crumbles. The goal is to provide tips, tools, and recipes from things that can commonly be found in the natural environment or in abandoned stores. Things from the latter category will of course become less and less abundant, though, so aim to move towards self-sufficiency.

== Before the shit hits the fan

Pick a home base. If you aren't skipping town right away, then you'll need somewhere to ride out the storm, and potentially rebuild your life from when things settle down. Keep a few things in mind when choosing a location:

* Proximity to other homes (sometimes further away is better, depending on the emergency)
* Proximity to stores
* Number of possible entrances/exits
* Fireplace

Make a map of where your home base is, and where essential things are around it, like fresh water sources, and stores you can raid.

=== Emergency Kit

* Solar charger
* Canned foods
* Granola or Raw-food bars
* Organic, non-hybrid seeds
* Barley grass seeds
* Manual juicer
* Baking soda
* Painkillers
* Hydrogen peroxide
* Compact cold-weather sleeping bag
* Compact two-man tent
* Emergency fire starter
* Waterproof matches
* Long johns
* Wool cap
* Wool socks
* Wool sweater
* Basic tool kit including:
* Nails
* Hammer
* A hardcover print version of your favorite book
* A print out of this book!

Know the most essential items in your closet you'd want to pack in a hurry. Write them here so you don't forget:

== When the shit hits the fan

# Gather supplies.
# Get to your home base.
# Secure the entrances, if necessary.
# Fill all tubs, sinks, and containers with water. You can distill it later if you want (see Water for details).

=== Looting/Scavenging List

Some of the items on this list are also on the Emergency Kit list. I'm going to assume you probably didn't worry too much about putting that together completely, because no sane person ever thinks the world's going to end - until it does.

When gathering the items on this list, you'll need to consider size and weight of the items, depending on whether you need to stay on the move or not. Also consider making multiple trips if you need to be in and out quickly.

Make a map of where the stores you'll need to go are, and the best routes to get between them and your home base. Also make an alternate route of stores along your way out of town.

.Grocery Store
* Energy bars
* Raw food bars
* Granola bars
* Green superfood powder
* Flax oil
* Raw honey
* Vitamins
* Water
* baking soda
* peppermint oil (secondary)

.Pharmacy
* Painkillers
* Antibiotics
* Toothpaste
* Toothbrushes
* Antiseptic, and/or
* Hydrogen peroxide
* Bandages (secondary)
* Tampons (secondary)
* Condoms (secondary)

.Sporting Goods store
* Compact cold-weather sleeping bag
* Compact cold-weather tent
* Compact cold-weather coat
* Wool socks
* Long johns
* Wool hat
* Backpack
* Emergency fire starter
* Waterproof matches
* Good shoes

.Harware store
* Seeds
* Locks
* Nails
* Hammer

== Travel

Make a plan
Where will you go?
Who do you know there?
What's their address, and how do you get there?
Print out the map/directions and put them in your kit.

Buy a bike
You may need to skip town, and a car isn't always a safe or reliable option. Here's what to keep in your bike kit:
* Small pump
* Spare tubes
* Patch kit
* Bike tool
* LED lights
* Helmet
* Lock
* Printed-out maps or a travel map book

Use your car and bike together
Drive as far as you can, and then when you can no longer get gas, switch to the bike.

== Sustenance

Ration your stores, right from the beginning.

Getting seeds is great, but when the shit starts to go down, get food you can eat now first. It's no use planning for the future if you have nothing to sustain yourself in the present.

=== Stocking Up

=== Planting and Growing

How to build a rooftop garden
Consider wind exposure and weight

http://www.theenvironmentsite.org/green-living-guides/eco-friendly-roof-walls/building-a-roof-garden/

Consider growing a nutritional grass
You can also do this in small containers in your home

http://bodyecology.com/articles/healthiest_grasses.php#.UQyXX0qLz0g

Let it grow into the grain a bit as well, which you can grind into flour or just eat

http://www.heirloom-organics.com/guide/va/guidetogrowingbarley.html

=== Foraging

=== Water

==== On the Move

Finding Water Sources:

==== At Home

Know where natural water supplies are, in relation to your home base. 

Get mineral supplements.

Rain water
Is the environment so over-polluted that the rain is unhealthy/toxic?

Distilling water: http://preparedforthat.com/diy-how-to-distill-water-at-home/
Use the stovetop method when cold out; you can use snow or natural ice to cool and condense the steam

=== Preparing for Winter

Drying foods

Canning

Storing
A root cellar

== Your Home

=== Locking it down

If the outside environment is so dangerous that you need to keep others out at all costs, you'll want to identify and seal-up the weak points in your home.

Use bookshelves or the shelves inside kitchen bainets as wood to cover windows or barricade doors
Use interior doors as wood for barricades
Table tops
Sides of dressers or bureaus
Cabinet doors

Find the safest room in your house and take measures to make it even safer.

=== Keeping it Fresh

Keep plants in your home, to help maintain a healthy supply of oxygen

Keep your home clean, to keep out vermin.

Open the fridge when the power goes out, so it doesn't mold. It can be used for storage or even as a last-resort safe-room for smaller folks (install some interior locks for real effectiveness).

Make sure you have ventilation for house-warming fires

== Protection

=== Guns

If you're not a gun person, now might be the time to change your mind. Staying away from guns in times of safety certainly makes sense, but there's no denying guns come in handy in times of emergency, when your life is constantly at risk. Here's a guide on what to look for, where to look, and what other supplies you'll need.

=== Knives

=== Homemade

A bow and arrows: 
http://www.wikihow.com/Make-a-Bow-and-Arrow

== Your Health

Garlic

Raw honey

Usnea (a lichen) can be used as an external antibiotic

Vitamin C: Citrus of course, but not readily available in all regions:
Sweet red pepper, sweet green pepper (eg, bell peppers)
Strawberries
Brussels sprouts
Cantaloupe
Pine needles

How to make a toothbrush
http://survival.outdoorlife.com/blogs/survivalist/2012/02/survival-skills-how-make-toothbrush-field

There will likely be an abundance of toothbrushes in the abandoned old stores, but you can fashion a rough one in a pinch.

Make a scrub with sugar or honey or tree sap/maple syrup or even sand and lemon juice, to use on your body

Lemons are prevalent in Florida and California, and are a very useful cleaning product. Use them for housecleaning too, but don't use them on very delicate fabrics.

Use olive oil or coconut oil to moisturize

Use aloe vera to moisturize

Or make nut or sunflower oil

http://www.ehow.com/how_5107984_make-almond-oil.html

How to make baking soda
http://www.youtube.com/watch?v=5KWdoWzzfsI

Toilet paper: moss can be used

== Cleaning

Laundry
If you're home-bound
If you have a home base, but can get out into the world
If you're travelling

== Miscellaneous

Making paper

Making ink

Making paint

Making fabric, Needles, Thread